---
- name: Compress directory ~/ in ~/foo.tgz and then Remove it
  hosts: ubuntu18,ubuntu20
  tasks:
    - name: Compress directory
      archive:
        path: ~/
        dest: ~/foo.tgz
    - name: list directory
      command: ls -l ~/
      register: list
    - debug: msg="{{ list.stdout }}"
    - debug: msg="{{ list.stderr }}"

    - name: Remove archive
      file: 
        path: ~/foo.tgz
        state: absent