---
- name: Deploy a jar file
  hosts: ubuntu18,ubuntu20
  remote_user: root
  tasks:
    - name: Installing java8 package
      apt:
        name: openjdk-8-jdk
        state: present
    - name: Copy jar file to home directory
      copy:
        src: ./target/*.jar
        dest: ~/
        mode: '0755'